/**
 * Seed data — realistic demo state.
 * In production this would be fetched from your API/DB.
 * Keeping it here isolates it from business logic.
 */

export const SEED_CLIENTS = [
  {
    id: "c1",
    name: "Aria Okonkwo",
    company: "Nova Media",
    email: "aria@novamedia.io",
    phone: "+1 415 555 0101",
    project: "Brand Identity Redesign",
    value: 4200,
    paid: 2100,
    status: "active",
    stage: "In Progress",
    lastContact: "2026-07-10",
    dueDate: "2026-08-15",
    invoicePending: true,
    tags: ["design", "branding"],
    notes: "Waiting on final logo approval. Client prefers async updates via email.",
    avatarIndex: 0,
    createdAt: "2026-05-01",
  },
  {
    id: "c2",
    name: "James Tran",
    company: "Tran Ventures",
    email: "james@tranventures.com",
    phone: "+1 646 555 0202",
    project: "E-commerce Site Build",
    value: 7800,
    paid: 0,
    status: "overdue",
    stage: "Review",
    lastContact: "2026-06-28",
    dueDate: "2026-07-20",
    invoicePending: true,
    tags: ["dev", "ecommerce"],
    notes: "Invoice #INV-003 sent 30 days ago. No response. Follow up urgently.",
    avatarIndex: 3,
    createdAt: "2026-04-15",
  },
  {
    id: "c3",
    name: "Priya Mehta",
    company: "LearnSpark",
    email: "priya@learnspark.co",
    phone: "+1 512 555 0303",
    project: "LMS Dashboard UI",
    value: 3100,
    paid: 3100,
    status: "active",
    stage: "Phase 2",
    lastContact: "2026-07-22",
    dueDate: "2026-09-01",
    invoicePending: false,
    tags: ["dev", "edtech"],
    notes: "Phase 1 delivered and approved. Phase 2 scoped. Great communicator.",
    avatarIndex: 1,
    createdAt: "2026-06-01",
  },
  {
    id: "c4",
    name: "Carlos Ruiz",
    company: "Ruiz Real Estate",
    email: "carlos@ruizestate.com",
    phone: "+1 305 555 0404",
    project: "SEO Content Package",
    value: 1800,
    paid: 1800,
    status: "completed",
    stage: "Delivered",
    lastContact: "2026-07-05",
    dueDate: "2026-07-01",
    invoicePending: false,
    tags: ["content", "seo"],
    notes: "All deliverables signed off. Strong candidate for a Q3 retainer.",
    avatarIndex: 2,
    createdAt: "2026-05-10",
  },
  {
    id: "c5",
    name: "Yuki Tanaka",
    company: "Tanaka Studio",
    email: "yuki@tanakastudio.jp",
    phone: "+81 3 555 0505",
    project: "Mobile App UI Kit",
    value: 5500,
    paid: 1500,
    status: "prospect",
    stage: "Proposal Sent",
    lastContact: "2026-07-18",
    dueDate: "2026-08-30",
    invoicePending: false,
    tags: ["design", "mobile"],
    notes: "Sent proposal 9 days ago. Very interested, awaiting board approval.",
    avatarIndex: 4,
    createdAt: "2026-07-01",
  },
];

export const SEED_INVOICES = [
  { id: "INV-001", clientId: "c1", client: "Aria Okonkwo",  amount: 2100, status: "paid",    date: "2026-06-15", due: "2026-06-30", desc: "Brand Identity – Phase 1 (50% deposit)" },
  { id: "INV-002", clientId: "c1", client: "Aria Okonkwo",  amount: 2100, status: "sent",    date: "2026-07-10", due: "2026-07-25", desc: "Brand Identity – Phase 2 (final balance)" },
  { id: "INV-003", clientId: "c2", client: "James Tran",    amount: 7800, status: "overdue", date: "2026-06-28", due: "2026-07-20", desc: "E-commerce Site Build – Full Project" },
  { id: "INV-004", clientId: "c3", client: "Priya Mehta",   amount: 3100, status: "paid",    date: "2026-07-01", due: "2026-07-15", desc: "LMS Dashboard – Phase 1" },
  { id: "INV-005", clientId: "c4", client: "Carlos Ruiz",   amount: 1800, status: "paid",    date: "2026-06-20", due: "2026-07-01", desc: "SEO Content Package – Delivery" },
  { id: "INV-006", clientId: "c5", client: "Yuki Tanaka",   amount: 1500, status: "paid",    date: "2026-07-05", due: "2026-07-15", desc: "Mobile App UI Kit – Kickoff deposit" },
];

export const SEED_TASKS = [
  { id: "t1", clientId: "c2", client: "James Tran",   text: "Send third invoice follow-up for INV-003",          done: false, due: "2026-07-29", priority: "high"   },
  { id: "t2", clientId: "c1", client: "Aria Okonkwo", text: "Share revised logo concepts (v3)",                  done: false, due: "2026-07-30", priority: "medium" },
  { id: "t3", clientId: "c5", client: "Yuki Tanaka",  text: "Follow up on proposal — decision expected this week", done: false, due: "2026-07-31", priority: "high"   },
  { id: "t4", clientId: "c3", client: "Priya Mehta",  text: "Schedule Phase 2 kickoff call",                     done: true,  due: "2026-07-22", priority: "medium" },
  { id: "t5", clientId: "c4", client: "Carlos Ruiz",  text: "Pitch Q3 content retainer package",                 done: false, due: "2026-08-05", priority: "low"    },
];

export const SEED_ACTIVITY = [
  { id: "a1", type: "alert",  icon: "🚨", text: "INV-003 from James Tran is 8 days overdue",        time: "Just now",  color: "#ef4444" },
  { id: "a2", type: "alert",  icon: "⚠️", text: "James Tran: 30 days without contact",              time: "Alert",     color: "#ef4444" },
  { id: "a3", type: "ai",     icon: "✨", text: "AI drafted check-in email for Yuki Tanaka",        time: "2h ago",    color: "#6366f1" },
  { id: "a4", type: "paid",   icon: "✅", text: "Priya Mehta paid INV-004 · $3,100 collected",      time: "3 days ago", color: "#22c55e" },
  { id: "a5", type: "update", icon: "📝", text: "Updated project notes for Aria Okonkwo",           time: "5 days ago", color: "#94a3b8" },
  { id: "a6", type: "new",    icon: "🎉", text: "New client added: Yuki Tanaka · $5,500 project",   time: "3 wks ago",  color: "#a855f7" },
];
